export enum NOTIFICATION_TYPE {
  FRIEND_INVITE = 'FRIEND_INVITE',
  FRIEND_INVITE_ACCEPT = 'FRIEND_INVITE_ACCEPT',
  FRIEND_INVITE_REJECT = 'FRIEND_INVITE_REJECT',
  USER_ONBOARD = 'USER_ONBOARD',
  BUSINESS_BOOKING_CREATE = 'BUSINESS_BOOKING_CREATE',
  BOOKING_CREATE = 'BOOKING_CREATE',
  BOKKING_ACCEPT = 'BOKKING_ACCEPT',
  BOOKING_REJECT = 'BOOKING_REJECT',
}

export enum NOTIFICATION {
  CALENDAR = 'CALENDAR',
  TASKS = 'TASKS',
  REMINDERS = 'REMINDERS',
  WAITLIST = 'WAITLIST',
  BOOKING = 'BOOKING',
  INVITES = 'INVITES',
  GENERAL = 'GENERAL'
}