export * from "./ProfileSetting";
export * from "./AccountSetting";
export * from "./ChangePassword";
export * from "./DeactivateAccount";
export * from "./LocationSetting";
export * from "./NotificationSetting";
export * from "./TermsCondition";
export * from "./ChangePersonalAssistant";
export * from "./ProfilePrivacy";
export * from "./HelpCenter";
export * from "./Feedback";
export * from "./ManageSubscription";
export * from "./SyncCalendar";
export * from "./PrivacyPolicy";
export * from './FriendDetails'
export * from './Profile'
export * from './QRcode'